# Generated by Django 5.1.1 on 2024-10-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
        ),
        migrations.AddField(
            model_name='favorite',
            name='place_id',
            field=models.CharField(default='Unknown Place ID', max_length=255),
        ),
        migrations.AddField(
            model_name='favorite',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
