# Generated by Django 5.1.1 on 2024-10-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favorite_address_favorite_place_id_favorite_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
