# Generated by Django 5.1.1 on 2024-10-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_review'),
        ('users', '0004_favorite_cuisine_type_favorite_phone_number_and_more'),
    ]

    operations = [
    ]
