# Generated by Django 5.1 on 2024-10-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtlantaFoodFinder', '0002_distances'),
        ('users', '0005_merge_20241002_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place_id',
            field=models.CharField(default='Unknown Place ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AtlantaFoodFinder.locations'),
        ),
    ]
