# Generated by Django 5.1.1 on 2024-09-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtlantaFoodFinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('driving', 'Driving'), ('walking', 'Walking'), ('bicycling', 'Bicycling'), ('transit', 'Transit')], max_length=20)),
                ('distance_km', models.FloatField()),
                ('duration_mins', models.IntegerField()),
                ('duration_traffic_mins', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_distances', to='AtlantaFoodFinder.locations')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_distances', to='AtlantaFoodFinder.locations')),
            ],
        ),
    ]
